"""DICOM rule data: generated from the standard (rules/standard/*.yaml) + local policy YAML.

- rules/standard/ps3.3_iod.yaml        Layer 1: IOD -> modules -> attribute Types (PS3.3),
                                        Modality / Body Part Examined Defined Terms
- rules/standard/ps3.15_e1-1_deid.yaml Layer 2: Basic Application Level Confidentiality
                                        Profile actions (PS3.15 Table E.1-1), CID 7050
- rules/deid_policy.yaml               site policy: profile options, pseudonym patterns,
                                        high-risk modalities for burned-in PHI
The two standard files are generated by scripts/build_iod_rules.py / build_deid_rules.py.
"""

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

IOD_RULES_FILE = "standard/ps3.3_iod.yaml"
DEID_RULES_FILE = "standard/ps3.15_e1-1_deid.yaml"
POLICY_FILE = "deid_policy.yaml"


def tag_label(tag: int) -> str:
    return f"({tag >> 16:04X},{tag & 0xFFFF:04X})"


# --- Layer 1 -------------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class AttributeSpec:
    tag: int
    keyword: str | None
    name: str
    type: str  # "1" | "1C" | "2" | "2C" | "3"
    level: int = 0

    @property
    def label(self) -> str:
        return self.keyword or self.name


@dataclass(frozen=True, slots=True)
class ModuleSpec:
    ref: str  # e.g. "C.7.6.2"
    name: str
    table: str  # e.g. "Table C.7-10"
    attributes: tuple[AttributeSpec, ...]

    @property
    def source(self) -> str:
        return f"PS3.3 {self.ref} {self.name} Module ({self.table})"


@dataclass(frozen=True, slots=True)
class ModuleUsage:
    module: ModuleSpec | None  # None for U modules (not loaded)
    name: str
    usage: str  # "M" | "C" | "U"
    condition: str | None


@dataclass(frozen=True, slots=True)
class FunctionalGroupSpec:
    macro: str
    ref: str
    usage: str
    per_frame_only: bool
    definition: ModuleSpec | None

    @property
    def sequence(self) -> AttributeSpec | None:
        if self.definition is None:
            return None
        top = [a for a in self.definition.attributes if a.level == 0]
        return top[0] if top else None

    @property
    def source(self) -> str:
        table = f" ({self.definition.table})" if self.definition else ""
        return f"PS3.3 {self.ref} {self.macro} Macro{table}"


@dataclass(frozen=True, slots=True)
class IodSpec:
    key: str
    name: str  # e.g. "CT Image IOD"
    table: str  # e.g. "Table A.3-1"
    sop_classes: tuple[str, ...]
    modalities: tuple[str, ...]
    modules: tuple[ModuleUsage, ...]
    functional_groups: tuple[FunctionalGroupSpec, ...] = ()
    functional_group_table: str | None = None

    @property
    def source(self) -> str:
        return f"PS3.3 {self.table} {self.name} Modules"

    def attribute_types(self) -> dict[int, str]:
        """Top-level tag -> strictest Type across mandatory modules (for X/Z/D resolution)."""
        order = {"1": 0, "1C": 1, "2": 2, "2C": 3, "3": 4}
        types: dict[int, str] = {}
        for usage in self.modules:
            if usage.module is None or usage.usage != "M":
                continue
            for attr in usage.module.attributes:
                current = types.get(attr.tag)
                if current is None or order[attr.type] < order[current]:
                    types[attr.tag] = attr.type
        return types


@dataclass(frozen=True, slots=True)
class ConformanceRules:
    iods: dict[str, IodSpec]
    by_sop_class: dict[str, str]
    by_modality: dict[str, str]
    modality_terms: frozenset[str]
    modality_retired_terms: frozenset[str]
    body_part_terms: frozenset[str]
    edition: str
    source_url: str


def _module(raw: dict[str, Any], ref: str, name: str | None = None) -> ModuleSpec:
    return ModuleSpec(
        ref=ref.removeprefix("sect_"),
        name=name or raw.get("name") or raw["caption"].removesuffix(" Module Attributes"),
        table=raw["table"],
        attributes=tuple(
            AttributeSpec(
                tag=int(a["tag"], 16),
                keyword=a.get("keyword"),
                name=a["name"],
                type=a["type"],
                level=a.get("level", 0),
            )
            for a in raw["attributes"]
        ),
    )


def load_conformance_rules(path: Path) -> ConformanceRules:
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    modules = {ref: _module(m, ref) for ref, m in raw["modules"].items()}
    iods: dict[str, IodSpec] = {}
    for key, item in raw["iods"].items():
        fg = item.get("functional_groups") or {}
        iods[key] = IodSpec(
            key=key,
            name=item["caption"].removesuffix(" Modules"),
            table=item["table"],
            sop_classes=tuple(item["sop_classes"]),
            modalities=tuple(item["modalities"]),
            modules=tuple(
                ModuleUsage(
                    module=modules.get(m["ref"]),
                    name=m["module"],
                    usage=m["usage"],
                    condition=m.get("condition"),
                )
                for m in item["modules"]
            ),
            functional_groups=tuple(
                FunctionalGroupSpec(
                    macro=g["macro"],
                    ref=g["ref"].removeprefix("sect_"),
                    usage=g["usage"],
                    per_frame_only=g.get("per_frame_only", False),
                    definition=_module(g["definition"], g["ref"], g["macro"])
                    if g.get("definition")
                    else None,
                )
                for g in fg.get("macros", [])
            ),
            functional_group_table=fg.get("table"),
        )
    terms = raw["defined_terms"]
    return ConformanceRules(
        iods=iods,
        by_sop_class={uid: key for key, iod in iods.items() for uid in iod.sop_classes},
        by_modality={m: key for key, iod in iods.items() for m in iod.modalities},
        modality_terms=frozenset(terms["Modality"]["defined"]),
        modality_retired_terms=frozenset(terms["Modality"]["retired"]),
        body_part_terms=frozenset(terms["BodyPartExamined"]["defined"]),
        edition=raw["sources"]["ps3.3"]["edition"],
        source_url=raw["sources"]["ps3.3"]["url"],
    )


# --- Layer 2 -------------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class DeidRule:
    name: str
    keyword: str | None
    basic: str  # D, Z, X, K, C, U or a combination such as "X/Z/D"
    options: dict[str, str]  # option key -> action ("K" / "C")

    @property
    def label(self) -> str:
        return self.keyword or self.name


@dataclass(frozen=True, slots=True)
class DeidOption:
    key: str
    name: str
    code: str  # CID 7050 code value (scheme DCM)


@dataclass(frozen=True, slots=True)
class DeidProfile:
    by_tag: dict[int, DeidRule]
    repeating: dict[str, DeidRule]  # "60xx3000" style masks
    private: DeidRule
    options: dict[str, DeidOption]  # in Table E.1-1 column order
    cid7050: dict[tuple[str, str], str]  # (scheme, code) -> meaning
    edition: str
    source_url: str

    def lookup(self, tag: int) -> DeidRule | None:
        rule = self.by_tag.get(tag)
        if rule is not None:
            return rule
        hex_tag = f"{tag >> 16:04X}{tag & 0xFFFF:04X}"
        for mask, candidate in self.repeating.items():
            pattern = mask.upper().replace("X", "x")
            if all(m in ("x", h) for m, h in zip(pattern, hex_tag, strict=True)):
                return candidate
        return None


def load_deid_profile(path: Path) -> DeidProfile:
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    by_tag: dict[int, DeidRule] = {}
    repeating: dict[str, DeidRule] = {}
    private: DeidRule | None = None
    for item in raw["attributes"]:
        rule = DeidRule(
            name=item["name"],
            keyword=item.get("keyword"),
            basic=item["basic"],
            options=dict(item.get("options") or {}),
        )
        tag = str(item["tag"])
        if tag == "private":
            private = rule
        elif "x" in tag:
            repeating[tag] = rule
        else:
            by_tag[int(tag, 16)] = rule
    if private is None:
        raise ValueError("Table E.1-1 has no private attribute row")
    source = raw["sources"]["table_E.1-1"]
    return DeidProfile(
        by_tag=by_tag,
        repeating=repeating,
        private=private,
        options={
            key: DeidOption(key=key, name=o["name"], code=str(o["cid7050_code"]))
            for key, o in raw["options"].items()
        },
        cid7050={(c["scheme"], str(c["code"])): c["meaning"] for c in raw["cid7050"]},
        edition=f"{source['part']} {source['edition']}",
        source_url=source["url"],
    )


@dataclass(frozen=True, slots=True)
class PseudonymRule:
    pattern: re.Pattern[str] | None
    allow_empty: bool


@dataclass(frozen=True, slots=True)
class DeidPolicy:
    options: tuple[str, ...]
    honor_claimed_options: bool
    pseudonyms: dict[str, PseudonymRule]
    high_risk_modalities: frozenset[str]


def load_policy(path: Path, known_options: dict[str, DeidOption]) -> DeidPolicy:
    raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    options = tuple(raw.get("options") or ())
    unknown = [o for o in options if o not in known_options]
    if unknown:
        raise ValueError(f"unknown de-identification options in {path.name}: {unknown}")
    pseudonyms = {
        keyword: PseudonymRule(
            pattern=re.compile(spec["pattern"]) if spec.get("pattern") else None,
            allow_empty=bool(spec.get("allow_empty", True)),
        )
        for keyword, spec in (raw.get("pseudonymization") or {}).items()
    }
    return DeidPolicy(
        options=options,
        honor_claimed_options=bool(raw.get("honor_claimed_options", True)),
        pseudonyms=pseudonyms,
        high_risk_modalities=frozenset(raw.get("burned_in_high_risk_modalities") or ()),
    )


# --- bundle --------------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class DicomRules:
    conformance: ConformanceRules
    deid: DeidProfile
    policy: DeidPolicy
    files: tuple[str, ...] = field(default=())

    @property
    def source(self) -> str:
        return (
            f"PS3.3 {self.conformance.edition} (rules/{IOD_RULES_FILE}), "
            f"{self.deid.edition} Table E.1-1 (rules/{DEID_RULES_FILE}), "
            f"policy (rules/{POLICY_FILE})"
        )


def load_rules(rules_dir: Path) -> DicomRules:
    conformance = load_conformance_rules(rules_dir / IOD_RULES_FILE)
    deid = load_deid_profile(rules_dir / DEID_RULES_FILE)
    policy = load_policy(rules_dir / POLICY_FILE, deid.options)
    return DicomRules(
        conformance=conformance,
        deid=deid,
        policy=policy,
        files=(IOD_RULES_FILE, DEID_RULES_FILE, POLICY_FILE),
    )
